replicaCount: 1

image:
  repository: registry.gitlab.com/mycompany/admin
  pullPolicy: Always
  tag: "vadim-a00d16cb"

imagePullSecrets:
  - name: "regcred"

GKEmanagedCertificate:
  enabled: true

env:
  - name: NGINX_PORT
    value: "80"

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  annotations:
    cloud.google.com/backend-config: '{"default": "banana-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/tls-acme: "true"
    networking.gke.io/v1beta1.FrontendConfig: "banana-frontend-config"
  hosts:
    - host: example.com
      paths:
        - path: /*
          pathType: ImplementationSpecific
    - host: example.com
      paths:
        - path: /*
          pathType: ImplementationSpecific

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector:
  workload: application
