apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-gcp-secrets
spec:
  provider:
    gcpsm:
      projectID: my-gcp-project-id
      auth:
        workloadIdentity:
          # name of the cluster region
          clusterLocation: me-west1-a
          # name of the GKE cluster
          clusterName: banana-gke-cluster
          # projectID of the cluster (if omitted defaults to spec.provider.gcpsm.projectID)
          clusterProjectID: my-gcp-project-id
          # reference the sa from above
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
