apiVersion: v1
data:
  runner-registration-token: REPLACE_ME
  runner-token: REPLACE_ME
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: gitlab-runner
    meta.helm.sh/release-namespace: gitlab-runner
  creationTimestamp: "2024-02-26T13:12:12Z"
  labels:
    app.kubernetes.io/instance: gitlab-runner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: my-gcp-project-id
    app.kubernetes.io/version: 15.9.1
    helm.sh/chart: my-gcp-project-id.1.0
  name: gitlab-runner-registration-token
  namespace: gitlab-runner-secondary
  resourceVersion: "294814082"
  uid: f0221454-b6b7-427e-b3fc-05b7825c9468
type: Opaque
