apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-registration-token
  labels:
    helm.sh/chart: my-gcp-project-id.1.0
    app.kubernetes.io/name: my-gcp-project-id
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "15.9.1"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:  
  runner-registration-token: REPLACE_ME
