apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  # you can only have one ConfigConnectorContext per namespace
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: "{{ .Values.namespace }}"
spec:
  {{- toYaml .Values.CondfigConnectorContext.spec | nindent 2 }}