# Default values for backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: registry.gitlab.com/mycompany/backend
#  repository: busybox
#  tag: "latest"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "staging-90a819ef"

nginx:
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: "stable-alpine-slim"

migrations:
  migrateCommand: |
    cd db/migrations13 && \
    sqitch --verbose deploy db:$DB_URL
  image:
    repository: registry.gitlab.com/mycompany/backend
    pullPolicy: Always
    tag: "staging-f5d8f63f-migrations"


imagePullSecrets:
  - name: "regcred"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    iam.gke.io/gcp-service-account: service-account@my-gcp-project-id.iam.gserviceaccount.com
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: apple-backend

podAnnotations: {}

env:
  - name: SCHEMA
    value: "mycompany"
  - name: PORT
    value: "3000"
  - name: ATW_TOKEN_URL
    value: "https://apigw-test.5555.co.il/auth/oauth/v2/token"
  - name: ATW_SET_DATA_URL
    value: "https://apigw-test.5555.co.il/testOne/set_ext_data_atw"
  - name: ATW_REDIRECT_URL
    value: "https://wizmimun-tst.5555.co.il/login"
  - name: CAR_DETAILS_SCOPE
    value: "read,write"
  - name: "FEATURES_OTP"
    value: "true"
  - name: MIMUN_TOKEN_URL
    value: "https://apigw-test.5555.co.il/auth/oauth/v2/token"
  - name: MIMUN_SEND_OTP_URL
    value: "https://apigw-test.5555.co.il/testOne/send_otp"
  - name: MIMUN_VERIFY_OTP_URL
    value: "https://apigw-test.5555.co.il/testOne/verify_otp"
  - name: MAKE_CALL_IVR_URL
    value: "https://apigw-test.5555.co.il/testOne/make_call_ivr_wrp"
  - name: STORAGE_BUCKET
    value: "apple-mycompany"
  - name: STORAGE_DEST_KEY_PREFIX
    value: "users/"
  - name: PUBSUB_CREATE_CAR_SHORT_LINK_TOPIC
    value: "apple-generate-car-short-links"
  - name: MIMUN_CMS_FOOTER_URL
    value: "https://apigw-test.5555.co.il/testOne/get_content_umbraco_wrp"
  - name: BO_RECAPTCHA_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: BO_RECAPTCHA_SECRET_KEY
  - name: MIMUN_CLIENT
    valueFrom:
      secretKeyRef:
        name: backend
        key: MIMUN_CLIENT
  - name: MIMUN_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: backend
        key: MIMUN_CLIENT_SECRET
  - name: ATW_AUTH_TOKEN
    valueFrom:
      secretKeyRef:
        name: backend
        key: ATW_AUTH_TOKEN
  - name: CAR_DETAILS_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: backend
        key: CAR_DETAILS_CLIENT_ID
  - name: CAR_DETAILS_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: backend
        key: CAR_DETAILS_CLIENT_SECRET
  - name: ATW_ORIG_SYSTEM
    value: "SLICKCHAIN"
  - name: ATW_AUTH_TOKEN
    valueFrom:
      secretKeyRef:
        name: backend
        key: ATW_AUTH_TOKEN
  - name: CARSYNC_PASSWORD
    valueFrom:
       secretKeyRef:
         name: backend
         key: CARSYNC_PASSWORD
  - name: DB_READ_ONLY_URL
    valueFrom:
       secretKeyRef:
         name: backend
         key: DB_READ_ONLY_URL
  - name: DB_URL
    valueFrom:
       secretKeyRef:
         name: backend
         key: DB_URL
  - name: RECAPTCHA_SECRET_KEY
    valueFrom:
      secretKeyRef:
        key: RECAPTCHA_SECRET_KEY
        name: backend
  - name: RECAPTCHA_VERIFY_URL
    value: "https://www.google.com/recaptcha/api/siteverify" 
  - name: FAST_CHECK_URL
    valueFrom:
      configMapKeyRef:
        name: functions
        key: fast_check_http
  - name: GENERATE_SHORT_LINK_URL
    valueFrom:
      configMapKeyRef:
        name: functions
        key: generate_short_link
  - name: CARWIZ_LINKS_URL
    value: "https://example.com"
  - name: CAR_POST_VIEWS_URL
    valueFrom:
      configMapKeyRef:
        name: functions
        key: car_post_views
  - name: FILTER_TOPIC
    valueFrom:
      configMapKeyRef:
        name: pubsub
        key: filter_topic
  - name: GENERATE_SIGNED_URL_SECURED_URL
    valueFrom:
      configMapKeyRef:
        name: functions
        key: generate_signed_url_secured_url
  - name: GRAPHILE_LICENSE
    valueFrom:
      secretKeyRef:
        name: backend
        key: GRAPHILE_LICENSE
  - name: GRAPHQL_SYSTEM_USER_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: GRAPHQL_SYSTEM_USER_KEY
  - name: IMAGEKIT_URL
    valueFrom:
      secretKeyRef:
        name: backend
        key: IMAGEKIT_URL
  - name: IMAGEKIT_PUBLIC_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: IMAGEKIT_PUBLIC_KEY
  - name: IMAGEKIT_PRIVATE_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: IMAGEKIT_PRIVATE_KEY
  - name: MASKYOO_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: MASKYOO_KEY
  - name: MERGE_USER_TOPIC
    valueFrom:
      configMapKeyRef:
        name: pubsub
        key: merge_user_topic
  - name: MESSAGEBIRD_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: MESSAGEBIRD_ACCESS_KEY
  - name: MESSAGEBIRD_SIGNING_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: MESSAGEBIRD_SIGNING_KEY
  - name: NAME_PASSWORD
    valueFrom:
      secretKeyRef:
        name: backend
        key: NAME_PASSWORD
  - name: NODE_ENV
    value: "dev"
  - name: ORDER_VERIFICATION_BUCKET_NAME
    valueFrom:
      configMapKeyRef:
        name: buckets
        key: ORDER_VERIFICATION_BUCKET_NAME
  - name: ORDER_VERIFICATION_FOLDER_NAME
    valueFrom:
      configMapKeyRef:
        name: buckets
        key: ORDER_VERIFICATION_FOLDER_NAME
  - name: PUBSUB_NOTIFICATIONS_TOPIC
    valueFrom:
      configMapKeyRef:
        name: pubsub
        key: pubsub_notifications_topic
  - name: PUBSUB_SYSTEM_EVENTS_TOPIC
    valueFrom:
      configMapKeyRef:
        name: pubsub
        key: pubsub_system_events_topic
  - name: RECOMMENDATIONS_URL
    valueFrom:
      configMapKeyRef:
        name: functions
        key: generate_user_recommendations_on_demand
  - name: UNSUBSCRIBE_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: UNSUBSCRIBE_KEY
  - name: USER_PREFERENCES_TOPIC
    valueFrom:
      configMapKeyRef:
        name: pubsub
        key: user_preferences_topic

generateSignedUrl: https://us-central1-mycompany-97e29.cloudfunctions.net/apple-generate_signed_url
baseDomain: example.com

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  annotations:
    cloud.google.com/neg: '{"ingress": true}'

GKEmanagedCertificate:
  enabled: true

gceBackendConfig:
  enabled: true
  spec:
    customResponseHeaders:
      headers:
      - "Access-Control-Allow-Origin:*"
      - "Access-Control-Allow-Methods:GET, POST, OPTIONS"
      - "Access-Control-Allow-Headers:DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
      - "Access-Control-Expose-Headers:Content-Length,Content-Range"
    logging:
      enable: true
      sampleRate: 1.0
    healthCheck:
      checkIntervalSec: 30
      timeoutSec: 5
      healthyThreshold: 1
      unhealthyThreshold: 2
      type: HTTP
      requestPath: /health
      port: 80
    cdn:
      enabled: true
      cacheMode: CACHE_ALL_STATIC
      clientTtl: 3600
      defaultTtl: 3600
      maxTtl: 86400
      negativeCaching: true

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/tls-acme: "true"
    networking.gke.io/v1beta1.FrontendConfig: "apple-frontend-config"
  hosts:
    - host: example.com
      paths:
        - path: /*
          pathType: ImplementationSpecific
    - host: example.com
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi


nodeSelector:
  workload: application

