replicaCount: 1

image:
  repository: registry.gitlab.com/mycompany/carwizx
  pullPolicy: Always
  tag: "staging-3296de16"

imagePullSecrets:
  - name: "regcred"

GKEmanagedCertificate:
  enabled: true

gceBackendConfig:
  enabled: true
  spec:
    logging:
      enable: true
      sampleRate: 1.0

env:
  - name: PORT
    value: "3000"
  - name: PROJECT
    value: "my-gcp-project-id"
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: "mycompany.json"

    
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
  annotations:
    cloud.google.com/neg: '{"ingress": true}'

ingress:
  enabled: true
  annotations:
    # kubernetes.io/tls-acme: "true" # DO NOT USE THIS ANNOTATION WITH GKE ManagedCertificate
    networking.gke.io/v1beta1.FrontendConfig: "apple-frontend-config"
    networking.gke.io/managed-certificates: "apple-mycompany-x-managed-cert"
  hosts:
    - host: example.com
      paths:
        - path: /*
          pathType: ImplementationSpecific
    - host: example.com
      paths:
        - path: /*
          pathType: ImplementationSpecific

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector:
  workload: application
