# Default values for admin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.gitlab.com/mycompany/pro
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "staging-12345678"

imagePullSecrets:
  - name: "regcred"
nameOverride: ""
fullnameOverride: ""

GKEmanagedCertificate:
  enabled: true

env:
  - name: NGINX_PORT
    value: "80"

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  annotations:
    cloud.google.com/backend-config: '{"default": "apple-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/tls-acme: "true"
    networking.gke.io/v1beta1.FrontendConfig: "apple-frontend-config"
  hosts:
    - host: example.com
      paths:
        - path: /*
          pathType: ImplementationSpecific
    - host: example.com
      paths:
        - path: /*
          pathType: ImplementationSpecific

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector:
  workload: application

tolerations: []

affinity: {}
