apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: corn-frontend-config
  namespace: mycompany
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: "301"
  sslPolicy: corn-ssl-policy
