apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: grafana-apple
  namespace: {{ .Release.Namespace | quote }}
spec:
  domains:
    - {{ index .Values "kube-prometheus-stack" "grafana" "ingress" "hosts" 0 }}

---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: influxdb-apple
  namespace: {{ .Release.Namespace | quote }}
spec:
  domains:
    - {{ .Values.influxdb.ingress.hostname }}
