apiVersion: v1
kind: Namespace
metadata:
  name: mycompany

---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets

---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns

---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-runner