apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-nginx-conf
data:
  default.conf: REPLACE_ME
    server {
      listen 80;
      proxy_max_temp_file_size 0;
      location /health {
        proxy_pass http:REPLACE_ME
      }

       location /ready {
        proxy_pass http:REPLACE_ME
      }

      location /graphql {
        proxy_pass http:REPLACE_ME
        if ($request_method = 'OPTIONS') {
          add_header 'Access-Control-Max-Age' 1728000;
          add_header 'Content-Type' 'text/plain; charset=utf-8';
          add_header 'Content-Length' 0;
          return 204;
        }
      }

      location /api/graphql {
        proxy_pass http:REPLACE_ME
        if ($request_method = 'OPTIONS') {
          add_header 'Access-Control-Max-Age' 1728000;
          add_header 'Content-Type' 'text/plain; charset=utf-8';
          add_header 'Content-Length' 0;
          return 204;
        }
      }

      client_max_body_size 5M;
      gzip_types text/plain text/css application/javascript text/xml application/xml+rss application/x-javascript application/json image/svg+xml;

      location /api/data/ {
        proxy_pass http:REPLACE_ME
        if ($request_method = 'OPTIONS') {
          add_header 'Access-Control-Max-Age' 1728000;
          add_header 'Content-Type' 'text/plain; charset=utf-8';
          add_header 'Content-Length' 0;
          return 204;
        }
      }

      location /api/functions/signed-url {
        if ($request_method = 'OPTIONS') {
          add_header 'Access-Control-Max-Age' 1728000;
          add_header 'Content-Type' 'text/plain; charset=utf-8';
          add_header 'Content-Length' 0;
          return 204;
        }
        proxy_pass {{ .Values.generateSignedUrl }};
      }

      location /api {

        proxy_pass http:REPLACE_ME
        if ($request_method = 'OPTIONS') {
          add_header 'Access-Control-Max-Age' 1728000;
          add_header 'Content-Type' 'text/plain; charset=utf-8';
          add_header 'Content-Length' 0;
          return 204;
        }
      }
    }

