replicaCount: 1

image:
  repository: registry.gitlab.com/mycompany/admin
  pullPolicy: Always
  tag: "vadim-a00d16cb"

imagePullSecrets:
  - name: "regcred"

GKEmanagedCertificate:
  enabled: true

env:
  - name: NGINX_PORT
    value: "80"
  - name: REACT_APP_UI_URL
    value: "https://example.com"
  - name: REACT_APP_AUDIT_URL
    value : "https://example.com"
  - name: REACT_APP_IMAGEKIT_AUTH_ENDPOINT
    value: "https://example.com/api/data/imagekit-auth"
  - name: REACT_APP_IMAGEKIT_URL
    value: "https://ik.imagekit.io/mycompany"
  - name: REACT_APP_FILTERS_VALIDATE_URL
    value: "https://us-central1-mycompany-dev.cloudfunctions.net/banana-fetch_custom_insights/validate_filters"
  - name: REACT_APP_CAR_NAMES_MANAGEMENT_URL
    value: "https://us-central1-mycompany-97e29.cloudfunctions.net/apple-car_names_management"
  - name: REACT_APP_BQ_TO_PG_TOPIC
    value: "apple-bq-to-pg"
  - name: REACT_APP_CAR_NAME_TABLE
    value: "name_tst"

  - name: REACT_APP_IMAGEKIT_PUBLIC_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: REACT_APP_IMAGEKIT_PUBLIC_KEY

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  annotations:
    cloud.google.com/backend-config: '{"default": "banana-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/tls-acme: "true"
    networking.gke.io/v1beta1.FrontendConfig: "banana-frontend-config"
  hosts:
    - host: example.com
      paths:
        - path: /*
          pathType: ImplementationSpecific
    - host: example.com
      paths:
        - path: /*
          pathType: ImplementationSpecific

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector:
  workload: application
