apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
  name: externalsecret-ui
  namespace: mycompany
spec:
  dataFrom:
  - find:
      decodingStrategy: None
      tags:
        environment: banana
        ui: "true"
    rewrite:
    - regexp:
        source: "BANANA_(.*)"
        target: "$1"
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-gcp-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: ui
