serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: service-account@my-gcp-project-id.iam.gserviceaccount.com
  name: "external-dns"

sources:
  - service
  - ingress

policy: sync

domainFilters: 
  - example.com
  - example.com

txtOwnerId: date

provider: google

nodeSelector:
  workload: infra