serviceAccount:
  create: true
  automount: true
  name: "external-secrets"
  annotations:
    iam.gke.io/gcp-service-account: service-account@my-gcp-project-id.iam.gserviceaccount.com

installCRDs: true

nodeSelector:
  workload: infra

webhook:
  nodeSelector:
    workload: infra

certController:
  nodeSelector:
    workload: infra