apiVersion: v1
kind: Service
metadata:
  name: docker-dind
  labels:
    {{- include "my-gcp-project-id.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.dind.port }}
      protocol: TCP
      targetPort: {{ .Values.service.dind.targetPort }}
  selector:
    app.kubernetes.io/name : {{ include "my-gcp-project-id.fullname" . }}-docker-dind