apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "my-gcp-project-id.labels" . | nindent 4 }}
    app.kubernetes.io/name : {{ include "my-gcp-project-id.fullname" . }}-docker-dind
  name: {{ include "my-gcp-project-id.fullname" . }}-dind-data
spec:
  storageClassName: {{ .Values.dindCacheStorageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dindCacheStorageSize }}