apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gitlab.runners.secret }}
  labels:
    {{- include "my-gcp-project-id.labels" . | nindent 4 }}
type: Opaque
data:
{{- ( include "gen.secret" . ) | indent 2 -}}
