# Default values for backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.gitlab.com/mycompany/backend/staging/backend13
#  repository: busybox
#  tag: "latest"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "4210deb51cae4eb76f5480c019bdcd003307689d"

nginx:
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: "stable-alpine-slim"

migrations:
  migrateCommand: |
    cd db/migrations13 && \
    sqitch --verbose deploy db:$DB_URL
  image:
    repository: registry.gitlab.com/mycompany/backend/staging/backend13-migrations13
    pullPolicy: Always
    tag: "4210deb51cae4eb76f5480c019bdcd003307689d"


imagePullSecrets:
  - name: "regcred"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    #iam.gke.io/gcp-service-account: service-account@my-gcp-project-id.iam.gserviceaccount.com
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

env:
  - name: SCHEMA
    value: "mycompany"
  - name: PORT
    value: "3000"
  - name: CARSYNC_PASSWORD
    valueFrom:
       secretKeyRef:
         name: backend
         key: CARSYNC_PASSWORD
  - name: CAR_DETAILS_URL
    valueFrom:
      configMapKeyRef:
        name: functions
        key: car_details
  - name: DB_READ_ONLY_URL
    valueFrom:
       secretKeyRef:
         name: backend
         key: DB_READ_ONLY_URL
  - name: DB_URL
    valueFrom:
       secretKeyRef:
         name: backend
         key: DB_URL
  - name: FAST_CHECK_URL
    valueFrom:
      configMapKeyRef:
        name: functions
        key: fast_check_http
  - name: FILTER_TOPIC
    valueFrom:
      configMapKeyRef:
        name: pubsub
        key: filter_topic
  - name: GENERATE_SIGNED_URL_SECURED_URL
    valueFrom:
      configMapKeyRef:
        name: functions
        key: generate_signed_url_secured_url
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: "./my-gcp-project-id.json"
  - name: GRAPHILE_LICENSE
    valueFrom:
      secretKeyRef:
        name: backend
        key: GRAPHILE_LICENSE
  - name: GRAPHQL_SYSTEM_USER_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: GRAPHQL_SYSTEM_USER_KEY
  - name: MASKYOO_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: MASKYOO_KEY
  - name: MERGE_USER_TOPIC
    valueFrom:
      configMapKeyRef:
        name: pubsub
        key: merge_user_topic
  - name: MESSAGEBIRD_SIGNING_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: MESSAGEBIRD_SIGNING_KEY
  - name: NAME_PASSWORD
    valueFrom:
      secretKeyRef:
        name: backend
        key: NAME_PASSWORD
  - name: NODE_ENV
    value: "dev"
  - name: ORDER_VERIFICATION_BUCKET_NAME
    valueFrom:
      configMapKeyRef:
        name: buckets
        key: ORDER_VERIFICATION_BUCKET_NAME
  - name: ORDER_VERIFICATION_FOLDER_NAME
    valueFrom:
      configMapKeyRef:
        name: buckets
        key: ORDER_VERIFICATION_FOLDER_NAME
  - name: PUBSUB_NOTIFICATIONS_TOPIC
    valueFrom:
      configMapKeyRef:
        name: pubsub
        key: pubsub_notifications_topic
  - name: PUBSUB_SYSTEM_EVENTS_TOPIC
    valueFrom:
      configMapKeyRef:
        name: pubsub
        key: pubsub_system_events_topic
  - name: RECOMMENDATIONS_URL
    valueFrom:
      configMapKeyRef:
        name: functions
        key: generate_user_recommendations_on_demand
  - name: UNSUBSCRIBE_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: UNSUBSCRIBE_KEY
  - name: USER_PREFERENCES_TOPIC
    valueFrom:
      configMapKeyRef:
        name: pubsub
        key: user_preferences_topic


generateSignedUrl: https://us-central1-mycompany-97e29.cloudfunctions.net/apple-generate_signed_url
baseDomain: example.com

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  annotations:
    cloud.google.com/neg: '{"ingress": true}'

GKEmanagedCertificate:
  enabled: true

gceBackendConfig:
  enabled: true
  spec:
    customResponseHeaders:
      headers:
      - "Access-Control-Allow-Origin:*"
      - "Access-Control-Allow-Methods:GET, POST, OPTIONS"
      - "Access-Control-Allow-Headers:DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
      - "Access-Control-Expose-Headers:Content-Length,Content-Range"
    logging:
      enable: true
      sampleRate: 1.0
    healthCheck:
      checkIntervalSec: 30
      timeoutSec: 5
      healthyThreshold: 1
      unhealthyThreshold: 2
      type: HTTP
      requestPath: /health
      port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/tls-acme: "true"
    networking.gke.io/v1beta1.FrontendConfig: "apple-frontend-config"
  hosts:
    - host: example.com
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


nodeSelector:
  workload: application

