# Default values for backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: registry.gitlab.com/mycompany/backend
#  repository: busybox
#  tag: "latest"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "master-13563424"

nginx:
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: "stable-alpine-slim"

migrations:
  migrateCommand: |
    cd db/migrations13 && \
    sqitch --verbose deploy db:$DB_URL
  image:
    repository: registry.gitlab.com/mycompany/backend
    pullPolicy: Always
    tag: "master-13563424-migrations"


imagePullSecrets:
  - name: "regcred"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    iam.gke.io/gcp-service-account: service-account@my-gcp-project-id.iam.gserviceaccount.com
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

env:
  - name: SCHEMA
    value: "mycompany"
  - name: PORT
    value: "3000"
  - name: PGPOOL_MAX_CONN
    value: "120"
  - name: ATW_TOKEN_URL
    value: "https://apigw.5555.co.il/auth/oauth/v2/token"
  - name: ATW_SET_DATA_URL
    value: "https://apigw.5555.co.il/prod/set_ext_data_atw"
  - name: ATW_REDIRECT_URL
    value: "https://WizMimun.5555.co.il/login"
  - name: CAR_DETAILS_SCOPE
    value: "read,write"
  - name: MIMUN_SEND_OTP_URL
    value: "https://apigw.5555.co.il/prod/send_otp"
  - name: MIMUN_VERIFY_OTP_URL
    value: "https://apigw.5555.co.il/prod/verify_otp"
  - name: FEATURES_OTP
    value: "true"
  - name: MAKE_CALL_IVR_URL
    value: "https://apigw.5555.co.il/prod/make_call_ivr_wrp"
  - name: STORAGE_BUCKET
    value: "date-mycompany"
  - name: STORAGE_DEST_KEY_PREFIX
    value: "users/"
  - name: PUBSUB_CREATE_CAR_SHORT_LINK_TOPIC
    value: "date-generate-car-short-links"
  - name: BO_RECAPTCHA_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: BO_RECAPTCHA_SECRET_KEY
  - name: MIMUN_CLIENT_SECRET
    valueFrom: 
      secretKeyRef:
        name: backend
        key: MIMUN_CLIENT_SECRET
  - name: MIMUN_CLIENT
    valueFrom: 
      secretKeyRef:
        name: backend
        key: MIMUN_CLIENT
  - name: MIMUN_TOKEN_URL
    valueFrom: 
      secretKeyRef:
        name: backend
        key: MIMUN_TOKEN_URL
  - name: ATW_AUTH_TOKEN
    valueFrom:
      secretKeyRef:
        name: backend
        key: ATW_AUTH_TOKEN
  - name: CAR_DETAILS_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: backend
        key: CAR_DETAILS_CLIENT_ID
  - name: CAR_DETAILS_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: backend
        key: CAR_DETAILS_CLIENT_SECRET
  - name: CARSYNC_PASSWORD
    valueFrom:
       secretKeyRef:
         name: backend
         key: CARSYNC_PASSWORD
  - name: DB_READ_ONLY_URL
    valueFrom:
       secretKeyRef:
         name: backend
         key: DB_READ_ONLY_URL
  - name: DB_URL
    valueFrom:
       secretKeyRef:
         name: backend
         key: DB_URL
  - name: FAST_CHECK_URL
    valueFrom:
      configMapKeyRef:
        name: functions
        key: fast_check_http
  - name: CAR_POST_VIEWS_URL
    valueFrom:
      configMapKeyRef:
        name: functions
        key: car_post_views
  - name: GENERATE_SHORT_LINK_URL
    valueFrom:
      configMapKeyRef:
        name: functions
        key: generate_short_link
  - name: FILTER_TOPIC
    valueFrom:
      configMapKeyRef:
        name: pubsub
        key: filter_topic
  - name: GENERATE_SIGNED_URL_SECURED_URL
    valueFrom:
      configMapKeyRef:
        name: functions
        key: generate_signed_url_secured_url
  - name: GRAPHILE_LICENSE
    valueFrom:
      secretKeyRef:
        name: backend
        key: GRAPHILE_LICENSE
  - name: GRAPHQL_SYSTEM_USER_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: GRAPHQL_SYSTEM_USER_KEY
  - name: IMAGEKIT_URL
    valueFrom:
      secretKeyRef:
        name: backend
        key: IMAGEKIT_URL
  - name: IMAGEKIT_PUBLIC_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: IMAGEKIT_PUBLIC_KEY
  - name: IMAGEKIT_PRIVATE_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: IMAGEKIT_PRIVATE_KEY
  - name: MASKYOO_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: MASKYOO_KEY
  - name: MERGE_USER_TOPIC
    valueFrom:
      configMapKeyRef:
        name: pubsub
        key: merge_user_topic
  - name: MESSAGEBIRD_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: MESSAGEBIRD_ACCESS_KEY
  - name: MESSAGEBIRD_SIGNING_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: MESSAGEBIRD_SIGNING_KEY
  - name: NAME_PASSWORD
    valueFrom:
      secretKeyRef:
        name: backend
        key: NAME_PASSWORD
  - name: NODE_ENV
    value: "dev"
  - name: ORDER_VERIFICATION_BUCKET_NAME
    valueFrom:
      configMapKeyRef:
        name: buckets
        key: order_verification_bucket_name
  - name: ORDER_VERIFICATION_FOLDER_NAME
    valueFrom:
      configMapKeyRef:
        name: buckets
        key: order_verification_folder_name
  - name: PUBSUB_NOTIFICATIONS_TOPIC
    valueFrom:
      configMapKeyRef:
        name: pubsub
        key: pubsub_notifications_topic
  - name: PUBSUB_SYSTEM_EVENTS_TOPIC
    valueFrom:
      configMapKeyRef:
        name: pubsub
        key: pubsub_system_events_topic
  - name: RECAPTCHA_SECRET_KEY
    valueFrom:
      secretKeyRef:
        key: RECAPTCHA_SECRET_KEY
        name: backend
  - name: RECAPTCHA_VERIFY_URL
    value: "https://www.google.com/recaptcha/api/siteverify" 
  - name: RECOMMENDATIONS_URL
    valueFrom:
      configMapKeyRef:
        name: functions
        key: generate_user_recommendations_on_demand
  - name: UNSUBSCRIBE_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: UNSUBSCRIBE_KEY
  - name: USER_PREFERENCES_TOPIC
    valueFrom:
      configMapKeyRef:
        name: pubsub
        key: user_preferences_topic


generateSignedUrl: https://example.com/generate_signed_url
baseDomain: example.com

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  annotations:
    cloud.google.com/neg: '{"ingress": true}'

GKEmanagedCertificate:
  enabled: true

gceBackendConfig:
  enabled: true
  spec:
    customResponseHeaders:
      headers:
      - "Access-Control-Allow-Origin:*"
      - "Access-Control-Allow-Methods:GET, POST, OPTIONS"
      - "Access-Control-Allow-Headers:DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
      - "Access-Control-Expose-Headers:Content-Length,Content-Range"
    logging:
      enable: true
      sampleRate: 1.0
    healthCheck:
      checkIntervalSec: 30
      timeoutSec: 5
      healthyThreshold: 1
      unhealthyThreshold: 2
      type: HTTP
      requestPath: /health
      port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: gce
    # kubernetes.io/tls-acme: "true"
    networking.gke.io/v1beta1.FrontendConfig: "date-frontend-config"
  hosts:
    - host: example.com
      paths:
        - path: /*
          pathType: ImplementationSpecific
    - host: example.com
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 1Gi

# autoscaling:
#   enabled: true
#   minReplicas: 3
#   maxReplicas: 6
#   targetCPUUtilizationPercentage: 80

nodeSelector:
  workload: application

